site_name: "Fluxify"
site_description: "No/Low Code Backend Engine to Build APIs with ease"
site_author: "07prajwal2000"
docs_dir: "./docs"
repo_name: "Fluxify"
repo_url: "https://www.github.com/fluxify-rest/Fluxify"
site_url: "https://docs.fluxify.rest"
edit_uri: "https://github.com/fluxify-rest/Fluxify/edit/main/docs/"
theme:
  name: material
  logo: "assets/logo.png"
  favicon: "assets/favicon.ico"
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.indexes
    - navigation.footer
    - navigation.sections

nav:
  - "Fluxify":
      - "index.md"
  - "Getting Started":
      - "getting-started/index.md"
      - "getting-started/basics.md"
      - "getting-started/installation.md"
      - "getting-started/contributing.md"
  - "Concepts":
      - "concepts/index.md"
      - App Config: "concepts/app-config.md"
      - Blocks: "concepts/blocks.md"
      - Edges: "concepts/edges.md"
      - Execution Engine: "concepts/execution-engine.md"
      - Globals: "concepts/globals.md"
      - Integrations: "concepts/integrations.md"
      - Virtual Machine: "concepts/vm.md"
      - HTTP Client: "concepts/http-client.md"
      - Evaluators: "concepts/evaluators.md"
      - Logging: "concepts/logging.md"
  - "Deployments":
      - "deployments/index.md"
      - Cloud: "deployments/cloud.md"
      - Kubernetes HA: "deployments/kubernetes-ha.md"
      - Serverless: "deployments/serverless.md"
      - Standalone Docker: "deployments/standalone-docker.md"
  - "Integrations":
      - "integrations/index.md"
      - "Databases":
          - "integrations/databases.md"
      - "Observability":
          - "integrations/observability.md"
      - "AI":
          - "integrations/ai-models.md"
  - "Scripting":
      - "scripting/index.md"
      - Context: "scripting/context.md"
      - How It Works: "scripting/how-it-works.md"
      - Key Considerations: "scripting/key-considerations.md"
      - npm Packages: "scripting/npm-packages.md"
  - "Blocks":
      - "blocks/index.md"
      - How They Work: "blocks/how-they-work.md"
      - List of Blocks: "blocks/list-of-blocks.md"
  - "Logs":
      - "blocks/cloud-logs.md"
      - "blocks/console-log.md"
  - "Blog":
      - "blog/index.md"
copyright: "Copyright &copy; 2025 Fluxify"
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/fluxify-rest/Fluxify
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/fluxify
markdown_extensions:
  - toc:
      permalink: true
      title: On This Page
      toc_depth: 3
  - def_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - tables
plugins:
  - search
  - blog:
      authors_profiles: true
      authors_profiles_name: Authors
  - tags:
      tags_allowed:
        - Built-in
        - Logic
        - Database
        - Logging
        - Misc
